/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_package;

import java.sql.Connection;
import java.sql.PreparedStatement;

import java.sql.DriverManager;
import java.sql.ResultSet;

import java.sql.SQLException;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author shain
 */
public class LoginForm extends javax.swing.JFrame {

    
    private  static final String username="root";
    private  static final String password="Shaini@2k";
    private  static final String dataCon="jdbc:mysql://localhost:3306/supermarketdb";
    
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        lbl_welcome = new javax.swing.JLabel();
        lbl_photo = new javax.swing.JLabel();
        lbl_loginIcon = new javax.swing.JLabel();
        lbl_userName = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        lbl_TopCover = new javax.swing.JLabel();
        txt_log_username = new javax.swing.JTextField();
        btn_signup = new javax.swing.JButton();
        btn_login = new javax.swing.JButton();
        btn_login1 = new javax.swing.JButton();
        pwdLogPassword = new javax.swing.JPasswordField();
        lbl_bottomCover = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLogin.setName("panelLogin"); // NOI18N
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_welcome.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_welcome.setForeground(new java.awt.Color(255, 255, 255));
        lbl_welcome.setText("WELCOME TO SUPERMARKET ");
        panelLogin.add(lbl_welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, -20, -1, 70));

        lbl_photo.setIcon(new javax.swing.ImageIcon("C:\\Users\\shain\\Documents\\NetBeansProjects\\EADcw\\login1.png")); // NOI18N
        panelLogin.add(lbl_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 80, 80));

        lbl_loginIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_loginIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\shain\\Documents\\NetBeansProjects\\EADcw\\lLogin.jpg")); // NOI18N
        lbl_loginIcon.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelLogin.add(lbl_loginIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 160, 110));

        lbl_userName.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        lbl_userName.setText("User  Name :");
        panelLogin.add(lbl_userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, 40));

        lbl_password.setFont(new java.awt.Font("Times New Roman", 1, 19)); // NOI18N
        lbl_password.setText("Password    :");
        panelLogin.add(lbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, 40));

        lbl_TopCover.setBackground(new java.awt.Color(255, 255, 255));
        lbl_TopCover.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_TopCover.setIcon(new javax.swing.ImageIcon("C:\\Users\\shain\\Documents\\NetBeansProjects\\EADcw\\istockphoto-1206800961-612x612.jpg")); // NOI18N
        lbl_TopCover.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        panelLogin.add(lbl_TopCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 520, 180));

        txt_log_username.setBackground(getBackground());
        txt_log_username.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_log_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_log_usernameActionPerformed(evt);
            }
        });
        panelLogin.add(txt_log_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 200, 30));

        btn_signup.setIcon(new javax.swing.ImageIcon("C:\\Users\\shain\\Documents\\NetBeansProjects\\EADcw\\sign-up.png")); // NOI18N
        btn_signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_signupMouseClicked(evt);
            }
        });
        btn_signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signupActionPerformed(evt);
            }
        });
        panelLogin.add(btn_signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 130, 40));

        btn_login.setBackground(new java.awt.Color(0, 0, 0));
        btn_login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_login.setForeground(new java.awt.Color(153, 153, 255));
        btn_login.setText("LOGIN");
        btn_login.setBorderPainted(false);
        btn_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_loginMouseClicked(evt);
            }
        });
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        panelLogin.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 120, 40));

        btn_login1.setIcon(new javax.swing.ImageIcon("C:\\Users\\shain\\Documents\\NetBeansProjects\\EADcw\\logButton.jpg")); // NOI18N
        btn_login1.setBorderPainted(false);
        panelLogin.add(btn_login1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 120, 40));

        pwdLogPassword.setBackground(getBackground());
        pwdLogPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pwdLogPassword.setText("Password");
        panelLogin.add(pwdLogPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 200, 30));

        lbl_bottomCover.setIcon(new javax.swing.ImageIcon("C:\\Users\\shain\\Documents\\NetBeansProjects\\EADcw\\coverr.jpg")); // NOI18N
        panelLogin.add(lbl_bottomCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 510, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelLogin.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_log_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_log_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_log_usernameActionPerformed

    private void btn_signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_signupActionPerformed

    private void btn_signupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_signupMouseClicked
      new RegisterForm().setVisible(true);
                   this.dispose();
    }//GEN-LAST:event_btn_signupMouseClicked

  
    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        
        
        
        String password1 =String.valueOf(pwdLogPassword.getPassword());
         String Uname= txt_log_username.getText();
        
        
        if(!"".equals(Uname) && !"".equals(password1)){
            
        
        
        
      try{
          
      
         Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataCon,username,password);
            pst = sqlConn.prepareStatement("Select UserName,Password from admins where UserName=? AND Password=?");
         
            
             pst.setString(1, txt_log_username.getText());
             pst.setString(2,password1);
            
           
            
            ResultSet rsl=pst.executeQuery();
             
            if(rsl.next()==false){
                JOptionPane.showMessageDialog(this,"Sorry UserName or password is Incorrect!");
                txt_log_username.setText("");
                pwdLogPassword.setText("");
                }
            
            
           
           
          
        
            else{
              new DashboardForm().setVisible(true);
                   this.dispose();
            }
     
      }
      
      catch(ClassNotFoundException ex){
             JOptionPane.showMessageDialog(this, ex, 
            "Error!", JOptionPane.CLOSED_OPTION);
        }
        catch (SQLException ex) {
            Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        }
        
        else{
             JOptionPane.showMessageDialog(this, "Fill all fields!", 
            "Error", JOptionPane.CLOSED_OPTION);   
        }
        
        
        
        
        
        
        
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_loginMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_loginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            LoginForm login=new LoginForm();
                   login.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_login1;
    private javax.swing.JButton btn_signup;
    private javax.swing.JLabel lbl_TopCover;
    private javax.swing.JLabel lbl_bottomCover;
    private javax.swing.JLabel lbl_loginIcon;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_photo;
    private javax.swing.JLabel lbl_userName;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPasswordField pwdLogPassword;
    private javax.swing.JTextField txt_log_username;
    // End of variables declaration//GEN-END:variables
}
