/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_package;

import java.sql.Connection;
import java.sql.PreparedStatement;

import java.sql.DriverManager;
import java.sql.ResultSet;

import java.sql.SQLException;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author shain
 */
public class RegisterForm extends javax.swing.JFrame {

    
    private  static final String username="root";
    private  static final String password="Shaini@2k";
    private  static final String dataCon="jdbc:mysql://localhost:3306/supermarketdb";
    
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regPanel = new javax.swing.JPanel();
        lbl_register = new javax.swing.JLabel();
        lbl_regPhoto = new javax.swing.JLabel();
        lbl_blue = new javax.swing.JLabel();
        lbl_EmpIDRegi = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblRePassword = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblArrow = new javax.swing.JLabel();
        txtRegEmpID = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtRePassword = new javax.swing.JPasswordField();
        lblCover = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        regPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_register.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        lbl_register.setForeground(new java.awt.Color(255, 255, 255));
        lbl_register.setText("REGISTER");
        regPanel.add(lbl_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 140, 40));

        lbl_regPhoto.setIcon(new javax.swing.ImageIcon("C:\\Users\\shain\\Documents\\NetBeansProjects\\EADcw\\register-icon.png")); // NOI18N
        regPanel.add(lbl_regPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 120, 120));

        lbl_blue.setIcon(new javax.swing.ImageIcon("C:\\Users\\shain\\Documents\\NetBeansProjects\\EADcw\\blue.png")); // NOI18N
        regPanel.add(lbl_blue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 170));

        lbl_EmpIDRegi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lbl_EmpIDRegi.setText("Employee ID           :");
        regPanel.add(lbl_EmpIDRegi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 170, -1));

        lblUserName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblUserName.setText("User Name              :");
        regPanel.add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 170, -1));

        lblPassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblPassword.setText("Password                :");
        regPanel.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 180, -1));

        lblRePassword.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblRePassword.setText("Confirm Password   :");
        regPanel.add(lblRePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 190, -1));

        btnSignUp.setIcon(new javax.swing.ImageIcon("C:\\Users\\shain\\Documents\\NetBeansProjects\\EADcw\\sign-button.jpg")); // NOI18N
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        regPanel.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 120, 40));

        btnBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\shain\\Documents\\NetBeansProjects\\EADcw\\backLogin.jpg")); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        regPanel.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, 100, -1));

        lblArrow.setIcon(new javax.swing.ImageIcon("C:\\Users\\shain\\Documents\\NetBeansProjects\\EADcw\\arrow.jpg")); // NOI18N
        regPanel.add(lblArrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 20, -1));

        txtRegEmpID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtRegEmpID.setForeground(new java.awt.Color(102, 102, 102));
        txtRegEmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegEmpIDActionPerformed(evt);
            }
        });
        regPanel.add(txtRegEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 210, 30));

        txtUserName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(102, 102, 102));
        regPanel.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 210, 30));

        txtPassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(102, 102, 102));
        txtPassword.setText("Password");
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        regPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 210, 30));

        txtRePassword.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtRePassword.setForeground(new java.awt.Color(102, 102, 102));
        txtRePassword.setText("Password");
        txtRePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtRePasswordMouseClicked(evt);
            }
        });
        txtRePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRePasswordActionPerformed(evt);
            }
        });
        regPanel.add(txtRePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 210, 30));

        lblCover.setIcon(new javax.swing.ImageIcon("C:\\Users\\shain\\Documents\\NetBeansProjects\\EADcw\\coverr.jpg")); // NOI18N
        regPanel.add(lblCover, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 500, 460));

        getContentPane().add(regPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        
        String password1 =String.valueOf(txtPassword.getPassword());
        String rePassword =String.valueOf(txtRePassword.getPassword());
        String EmpID= txtRegEmpID.getText();
        String Uname=txtUserName.getText();
        
        
        if(!"".equals(EmpID) && !"".equals(Uname) && !"".equals(password1) && !"".equals(rePassword)){
            
        
        
        
      try{
          
      
         Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataCon,username,password);
            pst = sqlConn.prepareStatement("Select EmployeeID from employee where EmployeeID=?");
         
            
             pst.setString(1, txtRegEmpID.getText());
             
            
           
            
            ResultSet rsl=pst.executeQuery();
            
            if(rsl.next()==false){
                JOptionPane.showMessageDialog(this,"Sorry that Employee ID is Not valid!");
                txtRegEmpID.setText("");
                txtUserName.setText("");
                txtPassword.setText("");
                txtRePassword.setText("");
                }
            
            
            
            else if(password1.equals(rePassword)){
               
                try{
            pst = sqlConn.prepareStatement("Insert into admins(EmployeeID,UserName,Password) Values (?,?,?)");
            
            pst.setString(1, txtRegEmpID.getText());
            pst.setString(2, txtUserName.getText());
            pst.setString(3, password1);
           
            
            pst.executeUpdate();
            
             JOptionPane.showMessageDialog(this, "Successfully Registered!", 
            "Saved", JOptionPane.CLOSED_OPTION);   

                }
                
               
       
        
        catch (SQLException ex) {
            Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
        }
      
            }
            
            else{
                JOptionPane.showMessageDialog(this, "Enter Same Password!", 
            "Error", JOptionPane.CLOSED_OPTION);   
            }
      }
      
      catch(ClassNotFoundException ex){
             JOptionPane.showMessageDialog(this, ex, 
            "Error!", JOptionPane.CLOSED_OPTION);
        }
        catch (SQLException ex) {
            Logger.getLogger(DashboardForm.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        }
        
        else{
             JOptionPane.showMessageDialog(this, "Fill all fields!", 
            "Error", JOptionPane.CLOSED_OPTION);   
        }
        
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void txtRegEmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegEmpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegEmpIDActionPerformed

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtRePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRePasswordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRePasswordMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        new LoginForm().setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnBackMouseClicked

    private void txtRePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRePasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel lblArrow;
    private javax.swing.JLabel lblCover;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRePassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lbl_EmpIDRegi;
    private javax.swing.JLabel lbl_blue;
    private javax.swing.JLabel lbl_regPhoto;
    private javax.swing.JLabel lbl_register;
    private javax.swing.JPanel regPanel;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRePassword;
    private javax.swing.JTextField txtRegEmpID;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
